name: Publish release

on:
  push:
    branches: [ "master" ]
    
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Create deploy folder
      run: mkdir -p ${GITHUB_WORKSPACE}/LightsOut
    - name: Copy HTML
      uses: canastro/copy-file-action@master
      with:
        source: "puzzle.html"
        target: "LightsOut/puzzle.html"
    - name: Copy CSS
      uses: canastro/copy-file-action@master
      with:
        source: "css"
        target: "LightsOut/css"
        flags: "-r"
    - name: Copy JS
      uses: canastro/copy-file-action@master
      with:
        source: "js"
        target: "LightsOut/js"
        flags: "-r"
    - name: Zip release
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r LightsOut.zip LightsOut
    - name: Get release name
      id: release_name
      run: echo "::set-output name=relname::$(date +'Build %Y-%m-%d %H:%M:%S')"
    - name: Get tag name
      id: tag_name
      run: echo "::set-output name=tagname::$(date +'%Y-%m-%d-%H-%M-%S')"
    - name: Create release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "LightsOut.zip"
        token: ${{secrets.GITHUB_TOKEN}}
        name: ${{steps.release_name.outputs.relname}}
        tag: ${{steps.tag_name.outputs.tagname}}
        commit: ${{github.sha}}
